---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Chart Builder

on:
  workflow_call:
    inputs:
      name:
        type: string
        description: Chart Name
        required: true
      version:
        type: string
        description: Chart Version
        required: true
      registry:
        type: string
        description: Chart Registry
        required: true
      release:
        type: boolean
        description: Release
        required: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      chart-exists: ${{ steps.chart.outputs.exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get Repository Name
        id: repository
        run: |
          echo "name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Check For Exising Chart
        uses: ./.github/actions/chart-exists
        id: chart
        with:
          chart: ${{ steps.repository.outputs.name }}/${{ inputs.name }}

  build:
    name: Build (${{ inputs.version }})
    runs-on: ubuntu-latest
    needs: ["prepare"]
    steps:
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - if: ${{ inputs.release }}
        name: Install Cosign
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2

      - if: ${{ inputs.release }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Add Helm Repository
        run: |
          helm repo add upstream ${{ inputs.registry }}

      - name: Update Helm Repository
        run: |
          helm repo update upstream

      - name: Pull Chart
        run: |
          helm pull upstream/${{ inputs.name }} --version ${{ inputs.version }}

      - if: ${{ inputs.release }}
        name: Push Chart
        run: |
          helm push *.tgz oci://ghcr.io/${{ github.repository }}

      - if: ${{ inputs.release }}
        name: Sign artifacts with Cosign
        run: |
          cosign sign --yes ghcr.io/${{ github.repository }}/${{ inputs.name }}:${{ inputs.version }}

  release:
    if: ${{ inputs.release && needs.prepare.outputs.chart-exists != 'true' }}
    name: Release
    needs: ["prepare", "build"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get Repository Name
        id: repository
        run: |
          echo "name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Generate Token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Get Release Tag
        uses: ./.github/actions/release-tag
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          body: |
            > [!NOTE]
            > A new chart has been added.

            ## 📦 Chart

            **Name**: [${{ inputs.name }}](https://github.com/${{ github.repository }}/pkgs/container/${{ steps.repository.outputs.name }}%2F${{ inputs.name }})
          tag: ${{ steps.release.outputs.tag }}
          token: ${{ steps.app-token.outputs.token }}

  notify:
    if: ${{ inputs.release && !cancelled() }}
    needs: ["prepare", "build", "release"]
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        name: Send Discord Webhook
        uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008 # v1.15.3
        with:
          color: "0xFF0000"
          description: |
            Name: `${{ inputs.name }}`
            Version: `${{ inputs.version }}`
            [Rebuild](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yaml)
          nodetail: true
          title: Chart build failed
          username: GitHub Actions
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
